name: Jenkins Automation

on:
  push:
    branches:
      - master

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        uses: https://github.com/Raplerttt/CoolKas.git/github-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "CoolKas Auto"
